/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "operator/pkg/apis/demo/v1"
	scheme "operator/pkg/client/clientset/versioned/scheme"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DemosGetter has a method to return a DemoInterface.
// A group's client should implement this interface.
type DemosGetter interface {
	Demos(namespace string) DemoInterface
}

// DemoInterface has methods to work with Demo resources.
type DemoInterface interface {
	Create(*v1.Demo) (*v1.Demo, error)
	Update(*v1.Demo) (*v1.Demo, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Demo, error)
	List(opts metav1.ListOptions) (*v1.DemoList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Demo, err error)
	DemoExpansion
}

// demos implements DemoInterface
type demos struct {
	client rest.Interface
	ns     string
}

// newDemos returns a Demos
func newDemos(c *SongV1Client, namespace string) *demos {
	return &demos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the demo, and returns the corresponding demo object, and an error if there is any.
func (c *demos) Get(name string, options metav1.GetOptions) (result *v1.Demo, err error) {
	result = &v1.Demo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("demos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Demos that match those selectors.
func (c *demos) List(opts metav1.ListOptions) (result *v1.DemoList, err error) {
	result = &v1.DemoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("demos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested demos.
func (c *demos) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("demos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a demo and creates it.  Returns the server's representation of the demo, and an error, if there is any.
func (c *demos) Create(demo *v1.Demo) (result *v1.Demo, err error) {
	result = &v1.Demo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("demos").
		Body(demo).
		Do().
		Into(result)
	return
}

// Update takes the representation of a demo and updates it. Returns the server's representation of the demo, and an error, if there is any.
func (c *demos) Update(demo *v1.Demo) (result *v1.Demo, err error) {
	result = &v1.Demo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("demos").
		Name(demo.Name).
		Body(demo).
		Do().
		Into(result)
	return
}

// Delete takes name of the demo and deletes it. Returns an error if one occurs.
func (c *demos) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("demos").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *demos) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("demos").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched demo.
func (c *demos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Demo, err error) {
	result = &v1.Demo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("demos").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
